In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,OneHotEncoder

In [2]:
final_df = pd.read_csv("../data/raw_data/job_salary_prediction_dataset.csv")

In [3]:
print(final_df.columns.tolist())

['job_title', 'experience_years', 'education_level', 'skills_count', 'industry', 'company_size', 'location', 'remote_work', 'certifications', 'salary']

In [3]:
df = pd.read_csv("../data/processed_data/clean_data.csv")

In [4]:
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

In [5]:
numericals_col = [col for col in df.columns if df[col].dtype in ["int64",float]]
categoricals_col = [col for col in df.columns if df[col].nunique()>1 and df[col].dtype == "str" and col != "Churn"]

### Encoding

In [6]:
encode = OneHotEncoder(handle_unknown='ignore',sparse_output=False)
df_encode = pd.DataFrame(
    encode.fit_transform(df[categoricals_col]),
    columns=encode.get_feature_names_out(categoricals_col),
    index = df.index 
)

In [7]:
scale = StandardScaler()
df_scale = pd.DataFrame(
    scale.fit_transform(df[numericals_col]),
    columns = scale.get_feature_names_out(numericals_col),
    index = df.index
)

In [8]:
df_scale

        experience_years  skills_count  certifications    salary
0              -0.000892     -1.459647       -0.288272 -0.970520
1              -0.825894      1.277940       -1.460281 -1.388854
2               1.319111     -1.094636       -0.874276  0.064289
3               1.484112      0.547917       -1.460281  1.160315
4               0.824110     -0.547118       -1.460281  0.517295
...                  ...           ...             ...       ...
249995          1.154111     -1.459647       -0.874276 -0.479233
249996          1.649112     -0.547118       -0.288272  0.237247
249997         -1.485896      0.365411       -1.460281 -1.864048
249998         -1.650897     -1.459647        1.469741 -1.476991
249999          0.989110     -1.459647        1.469741 -0.337738

[250000 rows x 4 columns]

In [9]:
final_df = pd.concat([df_scale,df_encode],axis=1)

In [13]:
final_df.to_csv("../data/processed_data/feature_data.csv", index=False)